// TCountries.DefaultLanguage property defines how TCountry.CommonName behaves
TCountries.DefaultLocale := 'fr';

// You may not need to change anything below this line

{$if defined(LANG_ab) or defined(LANG_ALL)}
  {$include locales\countries-ab.inc}
{$endif}
{$if defined(LANG_af) or defined(LANG_ALL)}
  {$include locales\countries-af.inc}
{$endif}
{$if defined(LANG_ak) or defined(LANG_ALL)}
  {$include locales\countries-ak.inc}
{$endif}
{$if defined(LANG_am) or defined(LANG_ALL)}
  {$include locales\countries-am.inc}
{$endif}
{$if defined(LANG_an) or defined(LANG_ALL)}
  {$include locales\countries-an.inc}
{$endif}
{$if defined(LANG_ar) or defined(LANG_ALL)}
  {$include locales\countries-ar.inc}
{$endif}
{$if defined(LANG_as) or defined(LANG_ALL)}
  {$include locales\countries-as.inc}
{$endif}
{$if defined(LANG_ay) or defined(LANG_ALL)}
  {$include locales\countries-ay.inc}
{$endif}
{$if defined(LANG_az) or defined(LANG_ALL)}
  {$include locales\countries-az.inc}
{$endif}
{$if defined(LANG_ba) or defined(LANG_ALL)}
  {$include locales\countries-ba.inc}
{$endif}
{$if defined(LANG_be) or defined(LANG_ALL)}
  {$include locales\countries-be.inc}
{$endif}
{$if defined(LANG_bg) or defined(LANG_ALL)}
  {$include locales\countries-bg.inc}
{$endif}
{$if defined(LANG_bi) or defined(LANG_ALL)}
  {$include locales\countries-bi.inc}
{$endif}
{$if defined(LANG_bn) or defined(LANG_ALL)}
  {$include locales\countries-bn.inc}
{$endif}
{$if defined(LANG_bn_IN) or defined(LANG_ALL)}
  {$include locales\countries-bn_IN.inc}
{$endif}
{$if defined(LANG_br) or defined(LANG_ALL)}
  {$include locales\countries-br.inc}
{$endif}
{$if defined(LANG_bs) or defined(LANG_ALL)}
  {$include locales\countries-bs.inc}
{$endif}
{$if defined(LANG_ca) or defined(LANG_ALL)}
  {$include locales\countries-ca.inc}
{$endif}
{$if defined(LANG_ce) or defined(LANG_ALL)}
  {$include locales\countries-ce.inc}
{$endif}
{$if defined(LANG_ch) or defined(LANG_ALL)}
  {$include locales\countries-ch.inc}
{$endif}
{$if defined(LANG_cs) or defined(LANG_ALL)}
  {$include locales\countries-cs.inc}
{$endif}
{$if defined(LANG_cv) or defined(LANG_ALL)}
  {$include locales\countries-cv.inc}
{$endif}
{$if defined(LANG_cy) or defined(LANG_ALL)}
  {$include locales\countries-cy.inc}
{$endif}
{$if defined(LANG_da) or defined(LANG_ALL)}
  {$include locales\countries-da.inc}
{$endif}
{$if defined(LANG_de) or defined(LANG_ALL)}
  {$include locales\countries-de.inc}
{$endif}
{$if defined(LANG_dv) or defined(LANG_ALL)}
  {$include locales\countries-dv.inc}
{$endif}
{$if defined(LANG_dz) or defined(LANG_ALL)}
  {$include locales\countries-dz.inc}
{$endif}
{$if defined(LANG_ee) or defined(LANG_ALL)}
  {$include locales\countries-ee.inc}
{$endif}
{$if defined(LANG_el) or defined(LANG_ALL)}
  {$include locales\countries-el.inc}
{$endif}
{$if defined(LANG_en) or defined(LANG_ALL)}
  {$include locales\countries-en.inc}
{$endif}
{$if defined(LANG_eo) or defined(LANG_ALL)}
  {$include locales\countries-eo.inc}
{$endif}
{$if defined(LANG_es) or defined(LANG_ALL)}
  {$include locales\countries-es.inc}
{$endif}
{$if defined(LANG_et) or defined(LANG_ALL)}
  {$include locales\countries-et.inc}
{$endif}
{$if defined(LANG_eu) or defined(LANG_ALL)}
  {$include locales\countries-eu.inc}
{$endif}
{$if defined(LANG_fa) or defined(LANG_ALL)}
  {$include locales\countries-fa.inc}
{$endif}
{$if defined(LANG_ff) or defined(LANG_ALL)}
  {$include locales\countries-ff.inc}
{$endif}
{$if defined(LANG_fi) or defined(LANG_ALL)}
  {$include locales\countries-fi.inc}
{$endif}
{$if defined(LANG_fo) or defined(LANG_ALL)}
  {$include locales\countries-fo.inc}
{$endif}
{$if defined(LANG_fr) or defined(LANG_ALL)}
  {$include locales\countries-fr.inc}
{$endif}
{$if defined(LANG_fy) or defined(LANG_ALL)}
  {$include locales\countries-fy.inc}
{$endif}
{$if defined(LANG_ga) or defined(LANG_ALL)}
  {$include locales\countries-ga.inc}
{$endif}
{$if defined(LANG_gl) or defined(LANG_ALL)}
  {$include locales\countries-gl.inc}
{$endif}
{$if defined(LANG_gn) or defined(LANG_ALL)}
  {$include locales\countries-gn.inc}
{$endif}
{$if defined(LANG_gu) or defined(LANG_ALL)}
  {$include locales\countries-gu.inc}
{$endif}
{$if defined(LANG_gv) or defined(LANG_ALL)}
  {$include locales\countries-gv.inc}
{$endif}
{$if defined(LANG_ha) or defined(LANG_ALL)}
  {$include locales\countries-ha.inc}
{$endif}
{$if defined(LANG_he) or defined(LANG_ALL)}
  {$include locales\countries-he.inc}
{$endif}
{$if defined(LANG_hi) or defined(LANG_ALL)}
  {$include locales\countries-hi.inc}
{$endif}
{$if defined(LANG_hr) or defined(LANG_ALL)}
  {$include locales\countries-hr.inc}
{$endif}
{$if defined(LANG_ht) or defined(LANG_ALL)}
  {$include locales\countries-ht.inc}
{$endif}
{$if defined(LANG_hu) or defined(LANG_ALL)}
  {$include locales\countries-hu.inc}
{$endif}
{$if defined(LANG_hy) or defined(LANG_ALL)}
  {$include locales\countries-hy.inc}
{$endif}
{$if defined(LANG_ia) or defined(LANG_ALL)}
  {$include locales\countries-ia.inc}
{$endif}
{$if defined(LANG_id) or defined(LANG_ALL)}
  {$include locales\countries-id.inc}
{$endif}
{$if defined(LANG_io) or defined(LANG_ALL)}
  {$include locales\countries-io.inc}
{$endif}
{$if defined(LANG_is) or defined(LANG_ALL)}
  {$include locales\countries-is.inc}
{$endif}
{$if defined(LANG_it) or defined(LANG_ALL)}
  {$include locales\countries-it.inc}
{$endif}
{$if defined(LANG_iu) or defined(LANG_ALL)}
  {$include locales\countries-iu.inc}
{$endif}
{$if defined(LANG_ja) or defined(LANG_ALL)}
  {$include locales\countries-ja.inc}
{$endif}
{$if defined(LANG_ka) or defined(LANG_ALL)}
  {$include locales\countries-ka.inc}
{$endif}
{$if defined(LANG_ki) or defined(LANG_ALL)}
  {$include locales\countries-ki.inc}
{$endif}
{$if defined(LANG_kk) or defined(LANG_ALL)}
  {$include locales\countries-kk.inc}
{$endif}
{$if defined(LANG_kl) or defined(LANG_ALL)}
  {$include locales\countries-kl.inc}
{$endif}
{$if defined(LANG_km) or defined(LANG_ALL)}
  {$include locales\countries-km.inc}
{$endif}
{$if defined(LANG_kn) or defined(LANG_ALL)}
  {$include locales\countries-kn.inc}
{$endif}
{$if defined(LANG_ko) or defined(LANG_ALL)}
  {$include locales\countries-ko.inc}
{$endif}
{$if defined(LANG_ku) or defined(LANG_ALL)}
  {$include locales\countries-ku.inc}
{$endif}
{$if defined(LANG_kv) or defined(LANG_ALL)}
  {$include locales\countries-kv.inc}
{$endif}
{$if defined(LANG_kw) or defined(LANG_ALL)}
  {$include locales\countries-kw.inc}
{$endif}
{$if defined(LANG_ky) or defined(LANG_ALL)}
  {$include locales\countries-ky.inc}
{$endif}
{$if defined(LANG_lo) or defined(LANG_ALL)}
  {$include locales\countries-lo.inc}
{$endif}
{$if defined(LANG_lt) or defined(LANG_ALL)}
  {$include locales\countries-lt.inc}
{$endif}
{$if defined(LANG_lv) or defined(LANG_ALL)}
  {$include locales\countries-lv.inc}
{$endif}
{$if defined(LANG_mi) or defined(LANG_ALL)}
  {$include locales\countries-mi.inc}
{$endif}
{$if defined(LANG_mk) or defined(LANG_ALL)}
  {$include locales\countries-mk.inc}
{$endif}
{$if defined(LANG_ml) or defined(LANG_ALL)}
  {$include locales\countries-ml.inc}
{$endif}
{$if defined(LANG_mn) or defined(LANG_ALL)}
  {$include locales\countries-mn.inc}
{$endif}
{$if defined(LANG_mr) or defined(LANG_ALL)}
  {$include locales\countries-mr.inc}
{$endif}
{$if defined(LANG_ms) or defined(LANG_ALL)}
  {$include locales\countries-ms.inc}
{$endif}
{$if defined(LANG_mt) or defined(LANG_ALL)}
  {$include locales\countries-mt.inc}
{$endif}
{$if defined(LANG_my) or defined(LANG_ALL)}
  {$include locales\countries-my.inc}
{$endif}
{$if defined(LANG_na) or defined(LANG_ALL)}
  {$include locales\countries-na.inc}
{$endif}
{$if defined(LANG_nb) or defined(LANG_ALL)}
  {$include locales\countries-nb.inc}
{$endif}
{$if defined(LANG_ne) or defined(LANG_ALL)}
  {$include locales\countries-ne.inc}
{$endif}
{$if defined(LANG_nl) or defined(LANG_ALL)}
  {$include locales\countries-nl.inc}
{$endif}
{$if defined(LANG_nn) or defined(LANG_ALL)}
  {$include locales\countries-nn.inc}
{$endif}
{$if defined(LANG_nv) or defined(LANG_ALL)}
  {$include locales\countries-nv.inc}
{$endif}
{$if defined(LANG_oc) or defined(LANG_ALL)}
  {$include locales\countries-oc.inc}
{$endif}
{$if defined(LANG_or) or defined(LANG_ALL)}
  {$include locales\countries-or.inc}
{$endif}
{$if defined(LANG_pa) or defined(LANG_ALL)}
  {$include locales\countries-pa.inc}
{$endif}
{$if defined(LANG_pi) or defined(LANG_ALL)}
  {$include locales\countries-pi.inc}
{$endif}
{$if defined(LANG_pl) or defined(LANG_ALL)}
  {$include locales\countries-pl.inc}
{$endif}
{$if defined(LANG_ps) or defined(LANG_ALL)}
  {$include locales\countries-ps.inc}
{$endif}
{$if defined(LANG_pt) or defined(LANG_ALL)}
  {$include locales\countries-pt.inc}
{$endif}
{$if defined(LANG_pt_BR) or defined(LANG_ALL)}
  {$include locales\countries-pt_BR.inc}
{$endif}
{$if defined(LANG_ro) or defined(LANG_ALL)}
  {$include locales\countries-ro.inc}
{$endif}
{$if defined(LANG_ru) or defined(LANG_ALL)}
  {$include locales\countries-ru.inc}
{$endif}
{$if defined(LANG_rw) or defined(LANG_ALL)}
  {$include locales\countries-rw.inc}
{$endif}
{$if defined(LANG_sc) or defined(LANG_ALL)}
  {$include locales\countries-sc.inc}
{$endif}
{$if defined(LANG_sd) or defined(LANG_ALL)}
  {$include locales\countries-sd.inc}
{$endif}
{$if defined(LANG_si) or defined(LANG_ALL)}
  {$include locales\countries-si.inc}
{$endif}
{$if defined(LANG_sk) or defined(LANG_ALL)}
  {$include locales\countries-sk.inc}
{$endif}
{$if defined(LANG_sl) or defined(LANG_ALL)}
  {$include locales\countries-sl.inc}
{$endif}
{$if defined(LANG_so) or defined(LANG_ALL)}
  {$include locales\countries-so.inc}
{$endif}
{$if defined(LANG_sq) or defined(LANG_ALL)}
  {$include locales\countries-sq.inc}
{$endif}
{$if defined(LANG_sr) or defined(LANG_ALL)}
  {$include locales\countries-sr.inc}
{$endif}
{$if defined(LANG_sv) or defined(LANG_ALL)}
  {$include locales\countries-sv.inc}
{$endif}
{$if defined(LANG_sw) or defined(LANG_ALL)}
  {$include locales\countries-sw.inc}
{$endif}
{$if defined(LANG_ta) or defined(LANG_ALL)}
  {$include locales\countries-ta.inc}
{$endif}
{$if defined(LANG_te) or defined(LANG_ALL)}
  {$include locales\countries-te.inc}
{$endif}
{$if defined(LANG_tg) or defined(LANG_ALL)}
  {$include locales\countries-tg.inc}
{$endif}
{$if defined(LANG_th) or defined(LANG_ALL)}
  {$include locales\countries-th.inc}
{$endif}
{$if defined(LANG_ti) or defined(LANG_ALL)}
  {$include locales\countries-ti.inc}
{$endif}
{$if defined(LANG_tk) or defined(LANG_ALL)}
  {$include locales\countries-tk.inc}
{$endif}
{$if defined(LANG_tl) or defined(LANG_ALL)}
  {$include locales\countries-tl.inc}
{$endif}
{$if defined(LANG_tr) or defined(LANG_ALL)}
  {$include locales\countries-tr.inc}
{$endif}
{$if defined(LANG_tt) or defined(LANG_ALL)}
  {$include locales\countries-tt.inc}
{$endif}
{$if defined(LANG_ug) or defined(LANG_ALL)}
  {$include locales\countries-ug.inc}
{$endif}
{$if defined(LANG_uk) or defined(LANG_ALL)}
  {$include locales\countries-uk.inc}
{$endif}
{$if defined(LANG_ur) or defined(LANG_ALL)}
  {$include locales\countries-ur.inc}
{$endif}
{$if defined(LANG_uz) or defined(LANG_ALL)}
  {$include locales\countries-uz.inc}
{$endif}
{$if defined(LANG_ve) or defined(LANG_ALL)}
  {$include locales\countries-ve.inc}
{$endif}
{$if defined(LANG_vi) or defined(LANG_ALL)}
  {$include locales\countries-vi.inc}
{$endif}
{$if defined(LANG_wa) or defined(LANG_ALL)}
  {$include locales\countries-wa.inc}
{$endif}
{$if defined(LANG_wo) or defined(LANG_ALL)}
  {$include locales\countries-wo.inc}
{$endif}
{$if defined(LANG_xh) or defined(LANG_ALL)}
  {$include locales\countries-xh.inc}
{$endif}
{$if defined(LANG_yo) or defined(LANG_ALL)}
  {$include locales\countries-yo.inc}
{$endif}
{$if defined(LANG_zh_CN) or defined(LANG_ALL)}
  {$include locales\countries-zh_CN.inc}
{$endif}
{$if defined(LANG_zh_HK) or defined(LANG_ALL)}
  {$include locales\countries-zh_HK.inc}
{$endif}
{$if defined(LANG_zh_TW) or defined(LANG_ALL)}
  {$include locales\countries-zh_TW.inc}
{$endif}
{$if defined(LANG_zu) or defined(LANG_ALL)}
  {$include locales\countries-zu.inc}
{$endif}
